### ISSUE TITLE
Please create a plugin

### ISSUE THREAD

**Issue by Chris2011** [allanlaal/Netbeans-Nightly-Multi-Autoinstall#1]
I know the problem, sometimes the updates of the plugins will update the ide too, but not often. Now I'm on the 20140910. I would really like to see this feature as a plugin, inside netbeans, maybe with a list, that I can choose an old one or so. This feature is really missing inside netbeans. The other problem is, I use windows and I want that the plugin works for the most platforms. I think this is possible. What do you think about it? Really nice tool.

Regards

Chris

**Comment by allanlaal** [comment]
Thank you for the suggestion :)
However this is written in Bash for *NIX systems (Ubuntu and debian mainly). A Netbeans plugin is in Java and is alot more complicated

I wrote this script so that I could add it to cron, which would automatically run every night and it would be separated from Netbeans itself.

I solved the issue of the selector by adding fixed shortcuts to the links on my toolbar:
/path/to/your/netbean/nightlies/netbeans-link-autonightly-0/path/to/netbeans/bin as Current
/path/to/your/netbean/nightlies/netbeans-link-autonightly-1/path/to/netbeans/bin as Previous
/path/to/your/netbean/nightlies/netbeans-link-autonightly-2/path/to/netbeans/bin as T -2days
/path/to/your/netbean/nightlies/netbeans-link-autonightly-3/path/to/netbeans/bin as T -3days
/path/to/your/netbean/nightlies/netbeans-link-autonightly-4/path/to/netbeans/bin as T -4days
/path/to/your/netbean/nightlies/netbeans-link-autonightly-5/path/to/netbeans/bin as T -5days
/path/to/your/netbean/nightlies/netbeans-link-autonightly-6/path/to/netbeans/bin as T -6days
... etc (if needed)

the script will update where the links are pointing, so you dont need to update any shortcuts after new nightlies are installed
I also have a symlink that I link manually to the latest known well working nightly, which I can use when I am not in the mood for playing around
